spring:
  application:
    name: @project.name@
  data:
    mongodb:
      uri: mongodb://localhost:27017
      username: root
      password: secret
      database: mydatabase

logging:
  level:
    com:
      mongodb: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
